// <auto-generated />
using System;
using AwardsFerm.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AwardsFerm.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.AdAccountEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GameTitle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GameUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenEncrypted")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ad_accounts", (string)null);
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.RsyaSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MonthReward")
                        .HasColumnType("TEXT");

                    b.Property<long>("TodayClicks")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TodayReward")
                        .HasColumnType("TEXT");

                    b.Property<long>("TodayShows")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId", "CapturedAt");

                    b.ToTable("rsya_snapshots", (string)null);
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.SessionRunEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameOverCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RuntimeSessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SessionSlotId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RuntimeSessionId");

                    b.HasIndex("SessionSlotId");

                    b.ToTable("session_runs", (string)null);
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.SessionSlotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("AdAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoRestart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ScheduleEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScheduledStartMsk")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("StopAtMsk")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdAccountId", "ProfileId")
                        .IsUnique();

                    b.ToTable("session_slots", (string)null);
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.UserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.AdAccountEntity", b =>
                {
                    b.HasOne("AwardsFerm.Api.Data.Entities.UserEntity", "User")
                        .WithMany("AdAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.RsyaSnapshotEntity", b =>
                {
                    b.HasOne("AwardsFerm.Api.Data.Entities.AdAccountEntity", "AdAccount")
                        .WithMany("RsyaSnapshots")
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdAccount");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.SessionRunEntity", b =>
                {
                    b.HasOne("AwardsFerm.Api.Data.Entities.SessionSlotEntity", "SessionSlot")
                        .WithMany("Runs")
                        .HasForeignKey("SessionSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SessionSlot");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.SessionSlotEntity", b =>
                {
                    b.HasOne("AwardsFerm.Api.Data.Entities.AdAccountEntity", "AdAccount")
                        .WithMany("SessionSlots")
                        .HasForeignKey("AdAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdAccount");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.AdAccountEntity", b =>
                {
                    b.Navigation("RsyaSnapshots");

                    b.Navigation("SessionSlots");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.SessionSlotEntity", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("AwardsFerm.Api.Data.Entities.UserEntity", b =>
                {
                    b.Navigation("AdAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
